
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Metrics generated by hbm2java
 */
@Entity
@Table(name = "metrics", catalog = "camcof")
public class Metrics implements java.io.Serializable {

	private Integer idMetrics;
	private String type;
	private String description;
	private String url;
	private Set<MidlevelInformation> midlevelInformations = new HashSet<MidlevelInformation>(
			0);

	public Metrics() {
	}

	public Metrics(String type, String url) {
		this.type = type;
		this.url = url;
	}

	public Metrics(String type, String description, String url,
			Set<MidlevelInformation> midlevelInformations) {
		this.type = type;
		this.description = description;
		this.url = url;
		this.midlevelInformations = midlevelInformations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMetrics", unique = true, nullable = false)
	public Integer getIdMetrics() {
		return this.idMetrics;
	}

	public void setIdMetrics(Integer idMetrics) {
		this.idMetrics = idMetrics;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "url", nullable = false, length = 99)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metrics")
	public Set<MidlevelInformation> getMidlevelInformations() {
		return this.midlevelInformations;
	}

	public void setMidlevelInformations(
			Set<MidlevelInformation> midlevelInformations) {
		this.midlevelInformations = midlevelInformations;
	}

}
